CREATE TABLE IF NOT EXISTS users (
    id SERIAL UNIQUE PRIMARY KEY NOT NULL,
    full_name CHARACTER VARYING(50) NOT NULL,
    message CHARACTER VARYING(150) NOT NULL,
    registered_on TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()
);